/**
 * Server Management Skill Initialization
 *
 * Auto-detects your project's server requirements and generates
 * customized start/stop scripts for development servers.
 *
 * Detects:
 * - Next.js dev servers (pages router, app router)
 * - Convex deployments
 * - Vite dev servers
 * - Custom npm scripts
 * - Port configuration
 * - Monorepo vs single app
 *
 * Usage:
 *   npx tsx .claude/skills/server-management/tools/init-server-scripts.ts
 *   npx tsx .claude/skills/server-management/tools/init-server-scripts.ts --port=3000
 */

import { execSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

interface ServerConfig {
  hasNextJs: boolean;
  hasConvex: boolean;
  hasVite: boolean;
  customDevCommand: string | null;
  recommendedPort: number;
  isMonorepo: boolean;
  monorepoApps: string[];
}

/**
 * Detect project server configuration
 */
function detectServerConfig(cwd: string): ServerConfig {
  const packageJsonPath = join(cwd, 'package.json');

  if (!existsSync(packageJsonPath)) {
    throw new Error(`package.json not found in ${cwd}`);
  }

  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
  const scripts = packageJson.scripts || {};
  const deps = { ...packageJson.dependencies, ...packageJson.devDependencies };

  // Detect Next.js
  const hasNextJs = !!deps.next || !!scripts.dev?.includes('next');

  // Detect Convex
  const hasConvex = !!deps.convex || existsSync(join(cwd, 'convex.json'));

  // Detect Vite
  const hasVite = !!deps.vite || !!scripts.dev?.includes('vite');

  // Detect monorepo (Turborepo, nx, lerna, workspaces)
  const isTurborepo = existsSync(join(cwd, 'turbo.json'));
  const hasWorkspaces = !!packageJson.workspaces;
  const isMonorepo = isTurborepo || hasWorkspaces;

  // Find monorepo apps
  let monorepoApps: string[] = [];
  if (isMonorepo && existsSync(join(cwd, 'apps'))) {
    try {
      const appsDir = join(cwd, 'apps');
      const apps = execSync(`ls ${appsDir}`, { encoding: 'utf-8' })
        .trim()
        .split('\n')
        .filter((app) => app && existsSync(join(appsDir, app, 'package.json')));
      monorepoApps = apps;
    } catch (e) {
      // Ignore errors
    }
  }

  // Determine recommended port
  let recommendedPort = 3000;
  if (hasNextJs) {
    // Check for custom Next.js port in dev script
    const devScript = scripts.dev || '';
    const portMatch = devScript.match(/--port[= ](\d+)/);
    if (portMatch) {
      recommendedPort = parseInt(portMatch[1], 10);
    } else {
      recommendedPort = 3000; // Next.js default
    }
  } else if (hasVite) {
    recommendedPort = 5173; // Vite default
  }

  // Find custom dev command
  const customDevCommand = scripts.dev || null;

  return {
    hasNextJs,
    hasConvex,
    hasVite,
    customDevCommand,
    recommendedPort,
    isMonorepo,
    monorepoApps,
  };
}

/**
 * Generate start-servers script based on detected configuration
 */
function generateStartScript(config: ServerConfig, cwd: string, customPort?: number): string {
  const port = customPort || config.recommendedPort;

  let script = `#!/bin/bash
# Auto-generated server startup script
# Generated by: .claude/skills/server-management/tools/init-server-scripts.ts
# Date: ${new Date().toISOString()}

set -e

echo "========================================"
echo "Starting Development Servers"
echo "========================================"

# Create .pids directory for process tracking
mkdir -p .pids

`;

  // Add Next.js startup
  if (config.hasNextJs) {
    if (config.isMonorepo && config.monorepoApps.length > 0) {
      // Monorepo: start first app by default
      const firstApp = config.monorepoApps[0];
      script += `
# Start Next.js dev server (Monorepo: apps/${firstApp})
echo "Starting Next.js dev server on port ${port}..."
cd apps/${firstApp}
npm run dev -- --port ${port} > ../../.pids/next.log 2>&1 &
NEXT_PID=$!
echo $NEXT_PID > ../../.pids/next.pid
cd ../..
echo "  Next.js PID: $NEXT_PID"

`;
    } else {
      // Single app
      script += `
# Start Next.js dev server
echo "Starting Next.js dev server on port ${port}..."
npm run dev -- --port ${port} > .pids/next.log 2>&1 &
NEXT_PID=$!
echo $NEXT_PID > .pids/next.pid
echo "  Next.js PID: $NEXT_PID"

`;
    }
  } else if (config.hasVite) {
    script += `
# Start Vite dev server
echo "Starting Vite dev server on port ${port}..."
npm run dev > .pids/vite.log 2>&1 &
VITE_PID=$!
echo $VITE_PID > .pids/vite.pid
echo "  Vite PID: $VITE_PID"

`;
  } else if (config.customDevCommand) {
    script += `
# Start custom dev server
echo "Starting dev server..."
npm run dev > .pids/dev.log 2>&1 &
DEV_PID=$!
echo $DEV_PID > .pids/dev.pid
echo "  Dev server PID: $DEV_PID"

`;
  }

  // Add Convex startup
  if (config.hasConvex) {
    if (config.isMonorepo && config.monorepoApps.length > 0) {
      const firstApp = config.monorepoApps[0];
      script += `
# Start Convex dev server (Monorepo: apps/${firstApp})
echo "Starting Convex dev server..."
cd apps/${firstApp}
npx convex dev > ../../.pids/convex.log 2>&1 &
CONVEX_PID=$!
echo $CONVEX_PID > ../../.pids/convex.pid
cd ../..
echo "  Convex PID: $CONVEX_PID"

`;
    } else {
      script += `
# Start Convex dev server
echo "Starting Convex dev server..."
npx convex dev > .pids/convex.log 2>&1 &
CONVEX_PID=$!
echo $CONVEX_PID > .pids/convex.pid
echo "  Convex PID: $CONVEX_PID"

`;
    }
  }

  script += `
echo ""
echo "Servers started successfully!"
`;

  if (config.hasNextJs) {
    script += `echo "  Next.js: http://localhost:${port}"
`;
  } else if (config.hasVite) {
    script += `echo "  Vite: http://localhost:${port}"
`;
  }

  if (config.hasConvex) {
    script += `echo "  Convex: Running in background"
`;
  }

  script += `
echo ""
echo "To stop servers: ./scripts/stop-servers.sh"
echo ""
`;

  return script;
}

/**
 * Generate stop-servers script
 */
function generateStopScript(config: ServerConfig): string {
  let script = `#!/bin/bash
# Auto-generated server shutdown script
# Generated by: .claude/skills/server-management/tools/init-server-scripts.ts
# Date: ${new Date().toISOString()}

echo "========================================"
echo "Stopping Development Servers"
echo "========================================"

`;

  // Add Next.js shutdown
  if (config.hasNextJs) {
    script += `
# Stop Next.js
if [ -f .pids/next.pid ]; then
  NEXT_PID=$(cat .pids/next.pid)
  echo "Stopping Next.js (PID: $NEXT_PID)..."
  kill $NEXT_PID 2>/dev/null || true
  rm .pids/next.pid
  rm .pids/next.log 2>/dev/null || true
  echo "  Next.js stopped"
else
  echo "  Next.js not running (no PID file)"
fi

`;
  } else if (config.hasVite) {
    script += `
# Stop Vite
if [ -f .pids/vite.pid ]; then
  VITE_PID=$(cat .pids/vite.pid)
  echo "Stopping Vite (PID: $VITE_PID)..."
  kill $VITE_PID 2>/dev/null || true
  rm .pids/vite.pid
  rm .pids/vite.log 2>/dev/null || true
  echo "  Vite stopped"
else
  echo "  Vite not running (no PID file)"
fi

`;
  } else if (config.customDevCommand) {
    script += `
# Stop dev server
if [ -f .pids/dev.pid ]; then
  DEV_PID=$(cat .pids/dev.pid)
  echo "Stopping dev server (PID: $DEV_PID)..."
  kill $DEV_PID 2>/dev/null || true
  rm .pids/dev.pid
  rm .pids/dev.log 2>/dev/null || true
  echo "  Dev server stopped"
else
  echo "  Dev server not running (no PID file)"
fi

`;
  }

  // Add Convex shutdown
  if (config.hasConvex) {
    script += `
# Stop Convex
if [ -f .pids/convex.pid ]; then
  CONVEX_PID=$(cat .pids/convex.pid)
  echo "Stopping Convex (PID: $CONVEX_PID)..."
  kill $CONVEX_PID 2>/dev/null || true
  rm .pids/convex.pid
  rm .pids/convex.log 2>/dev/null || true
  echo "  Convex stopped"
else
  echo "  Convex not running (no PID file)"
fi

`;
  }

  script += `
# Clean up .pids directory
if [ -d .pids ] && [ -z "$(ls -A .pids)" ]; then
  rmdir .pids
fi

echo ""
echo "Servers stopped successfully!"
echo ""
`;

  return script;
}

/**
 * Main initialization function
 */
async function initServerScripts(options: { port?: number } = {}) {
  const cwd = process.cwd();

  console.log('============================================================');
  console.log('Server Management Skill Initialization');
  console.log('============================================================\n');

  // Detect project configuration
  console.log('🔍 Detecting project configuration...\n');
  const config = detectServerConfig(cwd);

  console.log('📋 Detected Configuration:');
  console.log(`  Next.js: ${config.hasNextJs ? '✅' : '❌'}`);
  console.log(`  Convex: ${config.hasConvex ? '✅' : '❌'}`);
  console.log(`  Vite: ${config.hasVite ? '✅' : '❌'}`);
  console.log(`  Monorepo: ${config.isMonorepo ? '✅' : '❌'}`);
  if (config.isMonorepo) {
    console.log(`  Apps: ${config.monorepoApps.join(', ')}`);
  }
  console.log(`  Custom dev command: ${config.customDevCommand || '❌ None'}`);
  console.log(`  Recommended port: ${config.recommendedPort}\n`);

  // Generate scripts
  console.log('📝 Generating server management scripts...\n');

  const startScript = generateStartScript(config, cwd, options.port);
  const stopScript = generateStopScript(config);

  // Create scripts directory if it doesn't exist
  const scriptsDir = join(cwd, 'scripts');
  if (!existsSync(scriptsDir)) {
    mkdirSync(scriptsDir, { recursive: true });
  }

  // Write scripts
  const startScriptPath = join(scriptsDir, 'start-servers.sh');
  const stopScriptPath = join(scriptsDir, 'stop-servers.sh');

  writeFileSync(startScriptPath, startScript, { mode: 0o755 });
  writeFileSync(stopScriptPath, stopScript, { mode: 0o755 });

  console.log('✅ Scripts created successfully:\n');
  console.log(`  Start: ${startScriptPath}`);
  console.log(`  Stop: ${stopScriptPath}\n`);

  console.log('📖 Usage:\n');
  console.log('  # Start servers:');
  console.log('  ./scripts/start-servers.sh\n');
  console.log('  # Stop servers:');
  console.log('  ./scripts/stop-servers.sh\n');

  console.log('💡 Tips:\n');
  console.log('  - Scripts are auto-generated based on your project');
  console.log('  - Edit scripts if you need custom behavior');
  console.log('  - Re-run this script to regenerate with new settings');
  console.log('  - Use --port=<number> to customize the port\n');

  console.log('============================================================');
}

// CLI interface
const args = process.argv.slice(2);
const options: { port?: number } = {};

// Parse port argument
const portArg = args.find((arg) => arg.startsWith('--port='));
if (portArg) {
  options.port = parseInt(portArg.split('=')[1], 10);
}

// Show help
if (args.includes('--help') || args.includes('-h')) {
  console.log(`
Server Management Skill Initialization

Auto-detects your project's server requirements and generates
customized start/stop scripts.

Usage:
  npx tsx .claude/skills/server-management/tools/init-server-scripts.ts [options]

Options:
  --port=<number>     Custom port for dev server (default: auto-detect)
  --help, -h          Show this help message

Examples:
  # Auto-detect and generate scripts
  npx tsx .claude/skills/server-management/tools/init-server-scripts.ts

  # Generate scripts with custom port
  npx tsx .claude/skills/server-management/tools/init-server-scripts.ts --port=8765

What it detects:
  - Next.js (pages router, app router)
  - Convex deployments
  - Vite dev servers
  - Custom npm scripts
  - Monorepo structure (Turborepo, workspaces)
  - Port configuration

Output:
  - scripts/start-servers.sh (executable)
  - scripts/stop-servers.sh (executable)
  `);
  process.exit(0);
}

initServerScripts(options).catch((error) => {
  console.error('\n❌ Initialization error:', error);
  console.error('Stack trace:', error.stack);
  process.exit(1);
});
